os:
 - linux
 - osx

language: go

go: "1.10.x"

go_import_path: github.com/dcos/dcos-cli

env:
 - NO_DOCKER=1

before_script:
 - go get -u github.com/golang/dep/cmd/dep
 - go get -u github.com/golang/lint/golint
 - go get -u github.com/awalterschulze/goderive
 - go get -u github.com/br-lewis/go-bindata/...

script: make test
